// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using MOVIE_API.Models.Enum;

namespace MOVIE_API.Models;

public partial class BookingDetail
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int Id { get; set; }

    [Column(TypeName = "date")]
    public DateTime BookingDate { get; set; }

    [MaxLength(255)]
    [Column("comment")]
    public string Comment { get; set; }

    [ForeignKey("IdBooking")]
    public int IdBooking { get; set; }

    [ForeignKey("IdMovie")]
    public int IdMovie { get; set; }

    [Column(TypeName = "date")]
    public DateTime ReturnDate { get; set; }

    [Column(TypeName = "state")]
    public BookingDetailState? State { get; set; }

    [NotMapped]
    public string StateString
    {
        get
        {
            return State.HasValue ? State.ToString() : null;
        }
    }

    public virtual Booking IdBookingNavigation { get; set; }

    public virtual Movie IdMovieNavigation { get; set; }
}
