// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using MOVIE_API.Models.Enum;

namespace MOVIE_API.Models;

public partial class Booking
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int Id { get; set; }

    [ForeignKey("IdUser")]
    public int IdUser { get; set; }

    [Column(TypeName = "date")]
    public DateTime BookingDate { get; set; }

    [Column(TypeName = "date")]
    public DateTime? ReturnDate { get; set; }

    public int State { get; set; }

    public virtual ICollection<BookingDetail> BookingDetails { get; set; } = new List<BookingDetail>();

    public virtual User IdUserNavigation { get; set; }
}



