// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable


using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace MOVIE_API.Models;

public partial class User
{
    //Key: clave primaria o llave de la entidad 
    [Key]
    //Autogenero un Key por entidad creada en la BD: La opción Identity es que es autoincremental
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int Id { get; set; }

    [MaxLength(255)]
    [Column("email")]
    [Required]
    public string Email { get; set; }

    [MaxLength(255)]
    [Column("lastname")]
    public string Lastname { get; set; }

    [MaxLength(255)]
    [Column("name")]
    public string Name { get; set; }

    [MaxLength(255)]
    [Column("pass")]
    [Required]
    public string Pass { get; set; }

    [Column("rol")]
    public string Rol { get; set; }


    public virtual ICollection<Admin> Admins { get; set; } = new List<Admin>();

    public virtual ICollection<Booking> Bookings { get; set; } = new List<Booking>();

    public virtual ICollection<Client> Clients { get; set; } = new List<Client>();
}